export default {
    ru: {
        settings: 'Настройки',
        change_profile: 'Изменить профиль',
        language: 'Язык',
        logout: 'Выйти',
        back: 'Назад',
        save: 'Сохранить',
        next: 'Продолжить',
        firstName: 'Имя',
        lastName: 'Фамилия',
        city: 'Город',
        last_name_not_empty: 'Фамилия не может быть пустой',
        first_name_not_empty: 'Имя не может быть пустым',
        title_not_empty: 'Заголовок не может быть пустым',
        rooms: 'Комнаты',
        create_room: 'Создать комнату',
        something_goes_wrong: 'Что-то пошло не так...',
        chats: 'Чаты',
        notifications: 'Уведомления',
        contacts: 'Контакты',
        friends: 'Друзья',
        inbox: 'Входящие',
        outbox: 'Исходящие',
        you_dont_have_friends: 'У вас нет друзей, давайте добавим их',
        search: 'Поиск',
        message: 'Сообщение',
        call: 'Позвонить',
        accept: 'Принять',
        decline: 'Отклонить',
        not_indicated: 'Не указано',
        plus_friend: '+ Друг',
        remove: "Удалить",
        english: 'Английский',
        russian: 'Русский',
        you: 'Вы',
        write_message: 'Напишите сообщение...',
        show_investments: 'Показать вложения',
        you_sure: 'Вы уверены?',
        delete: 'Удалить',
        delete_room: 'Удалить комнату',
        invite_friends: 'Пригласить друзей',
        edit_room: 'Изменить комнату',
        investments: 'Вложения',
        photos: 'Фотографии',
        sounds: 'Аудио',
        files: 'Файлы',
        online: 'онлайн',
        missed_call: 'Пропущенный звонок',
        outcoming_call: 'Исходящий звонок',
        incoming_call: 'Входящий звонок',
        canceled_call: 'Отменённый звонок',
        select_language: 'Выберите язык',
        users_not_found: 'Пользователи не найдены',
        user_not_found: 'Пользователь не найден',
        reply: 'Ответить',
        forward: 'Переслать',
        title: 'Название',
        new_room: 'Новая комната',
        invite: 'Пригласить',
        private_room: 'Приватная комната',
        start: 'Начать',
        select_users: 'Выберите пользователей',
        new_chat: 'Новый чат',
        invited_you_to_the_room: 'Пригласил(а) вас в комнату',
        accept_your_friend_request: 'Принял(а) ваш запрос в друзья',
        send_you_friend_request: 'Отправил(а) вам запрос в друзья',
        january: 'Январь',
        february: 'Февраль',
        march: 'Март',
        april: 'Апрель',
        may: 'Май',
        june: 'Июнь',
        july: 'Июль',
        august: 'Август',
        september: 'Сентябрь',
        october: 'Октябрь',
        november: 'Ноябрь',
        december: 'Декабрь',
        jan: 'Янв',
        feb: 'Фев',
        mar: 'Мар',
        apr: 'Апр',
        jun: 'Июн',
        jul: 'Июл',
        aug: 'Авг',
        sep: 'Сен',
        oct: 'Окт',
        nov: 'Ноя',
        dec: 'Дек',
        in: 'в',
        yerstaday: 'вчера',
        today: 'сегодня',
        just_now: 'только что'
    },
    en: {
        settings: 'Settings',
        change_profile: 'Change profile',
        language: 'Language',
        logout: 'Logout',
        back: 'Back',
        save: 'Save',
        next: 'Next',
        firstName: 'First name',
        lastName: 'Last name',
        city: 'City',
        last_name_not_empty: 'First name cannot be empty',
        first_name_not_empty: 'Last name cannot be empty',
        title_not_empty: 'Title cannot be empty',
        rooms: 'Rooms',
        create_room: 'Create room',
        something_goes_wrong: 'Something goes wrong...',
        chats: 'Chats',
        notifications: 'Notifications',
        contacts: 'Contacts',
        friends: 'Friends',
        inbox: 'Inbox',
        outbox: 'Outbox',
        you_dont_have_friends: 'You dont have friends, lets add him',
        search: 'Search',
        message: 'Message',
        call: 'Call',
        accept: 'Accept',
        decline: 'Decline',
        not_indicated: 'Not indicated',
        plus_friend: '+ Friend',
        remove: "Remove",
        english: 'English',
        russian: 'Russian',
        you: 'You',
        write_message: 'Write message...',
        show_investments: 'Show investments',
        outcoming_call: 'Outcoming call',
        incoming_call: 'Incoming call',
        online: 'online',
        invite: 'Invite',
        delete_room: 'Delete room',
        invite_friends: 'Invite friends',
        edit_room: 'Edit room',
        you_sure: 'You sure?',
        delete: 'Delete',
        investments: 'Investments',
        photos: 'Photos',
        sounds: 'Sounds',
        files: 'Files',
        missed_call: 'Missed call',
        canceled_call: 'Canceled call',
        select_language: 'Select language',
        users_not_found: 'Users not found',
        user_not_found: 'User not found',
        reply: 'Reply',
        forward: 'Forward',
        title: 'Title',
        new_room: 'New room',
        private_room: 'Private room',
        start: 'Start',
        select_users: 'Select users',
        new_chat: 'New chat',
        invited_you_to_the_room: 'Invited you to the room',
        accept_your_friend_request: 'Accept your friend request',
        send_you_friend_request: 'Send you friend request',
        january: 'January',
        february: 'February',
        march: 'March',
        april: 'April',
        may: 'May',
        june: 'June',
        july: 'July',
        august: 'August',
        september: 'September',
        october: 'October',
        november: 'November',
        december: 'December',
        jan: 'Jan',
        feb: 'Feb',
        mar: 'Mar',
        apr: 'Apr',
        jun: 'Jun',
        jul: 'Jul',
        aug: 'Aug',
        sep: 'Sep',
        oct: 'Oct',
        nov: 'Nov',
        dec: 'Dec',
        in: 'in',
        yerstaday: 'yerstaday',
        today: 'Today',
        just_now: 'just now'
    }
}